version: '3'
services:

  directory:
    image: asyx.distributed.example/basyx-distributed-example-directory-vab:latest
    ports:
      - 127.0.0.1:8081:8080
  oven: 
    image: asyx.distributed.example/basyx-distributed-example-oven:latest
    depends_on: 
      - directory
    ports:
      - 127.0.0.1:8082:8080
  oven-control: 
    image: asyx.distributed.example/basyx-distributed-example-oven-control:latest
    ports:
      - 127.0.0.1:8080:8080
    depends_on: 
      - directory
      - oven
