version: '3'
services:

  directory:
    image: basyx.distributed.example/basyx-distributed-example-directory-vab:latest
    ports:
      - 127.0.0.1:8080:8080
  oven: 
    image: basyx.distributed.example/basyx-distributed-example-oven:latest
    ports:
      - 127.0.0.1:4000:4000
    depends_on: 
      - directory
