# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OP maven repository
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: op-custom-repo # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_REPO_USER
        server-password: MAVEN_REPO_PASS
    - name: Build with Maven
      env:
        MAVEN_REPO_USER: maven-github-access
        MAVEN_REPO_PASS: ${{ secrets.MAVEN_OP_REPOSITORY_PASS }}
      run: mvn -B install
